const samples={
 arduino:{title:'Arduino Standalone',subtitle:'Arduino Uno R3 · 5V · PID + MPU6050 + L298N',controller:'Arduino UNO R3',controllerPins:[['MPU6050 I2C','A4 SDA / A5 SCL'],['MPU INT','D2'],['IR OUT','D3'],['ENA / ENB PWM','D5 / D10'],['LEFT DIR','D6 / D7'],['RIGHT DIR','D8 / D9'],['HC-SR04','A0 TRIG / A1 ECHO'],['LEDs','D11 / D12 / D13 / D4']],components:[
{id:'arduino',type:'controller',label:'ARDUINO UNO R3',x:60,y:190,w:230,h:300,fill:'#e8f2ff'},
{id:'mpu',type:'sensor',label:'MPU6050',sub:'I2C · VCC · GND · SDA · SCL',x:380,y:90,w:230,h:105,fill:'#dcecff'},
{id:'sonar',type:'sensor',label:'HC-SR04',sub:'TRIG / ECHO · obstacle safety',x:365,y:430,w:230,h:100,fill:'#fff3c4'},
{id:'driver',type:'driver',label:'L298N DUAL H-BRIDGE',sub:'ENA D5 · IN1 D6 · IN2 D7 · IN3 D8 · IN4 D9 · ENB D10',x:330,y:270,w:310,h:125,fill:'#f05b28'},
{id:'left',type:'motor',label:'LEFT MOTOR',sub:'OUT1 / OUT2',x:15,y:330,w:150,h:82,fill:'#e7fff0'},
{id:'right',type:'motor',label:'RIGHT MOTOR',sub:'OUT3 / OUT4',x:680,y:330,w:150,h:82,fill:'#e7fbff'},
{id:'led',type:'status',label:'STATUS LEDs ×4',sub:'D11 · D12 · D13 · D4 · 220Ω each',x:70,y:535,w:290,h:78,fill:'#ffe8eb'},
{id:'battery',type:'power',label:'BATTERY + SWITCH',sub:'motor supply only',x:590,y:515,w:225,h:98,fill:'#fff0ae'}],connections:[
['arduino','mpu','A4 → SDA','i2c'],['arduino','mpu','A5 → SCL','i2c'],['arduino','mpu','5V → VCC','power'],['arduino','driver','D5/D10 → ENA/ENB','control'],['arduino','driver','D6/D7/D8/D9 → DIR','control'],['arduino','sonar','A0 → TRIG · A1 ← ECHO','sensor'],['driver','left','OUT1 / OUT2','motorL'],['driver','right','OUT3 / OUT4','motorR'],['battery','driver','VMOTOR +','power'],['arduino','led','D11/D12/D13/D4','signal'],['arduino','driver','GND مشترک','gnd']]},
 esp32:{title:'ESP32 Standalone',subtitle:'ESP32 DevKit · 3.3V · Wi‑Fi + PID + MPU6050 + L298N',controller:'ESP32 DEVKIT',controllerPins:[['MPU6050 I2C','GPIO21 SDA / GPIO22 SCL'],['MPU INT','GPIO39 reserved'],['ENA / ENB PWM','GPIO27 / GPIO14'],['LEFT DIR','GPIO32 / GPIO33'],['RIGHT DIR','GPIO25 / GPIO26'],['HC-SR04','GPIO5 TRIG / GPIO34 ECHO'],['IR OUT','GPIO2'],['LEDs','GPIO4 / 16 / 17 / 23'],['MODE_PIN','GPIO35 input-only']],components:[
{id:'esp',type:'controller',label:'ESP32 DEVKIT',sub:'3.3V standalone controller',x:60,y:150,w:235,h:350,fill:'#e8f2ff'},
{id:'mpu',type:'sensor',label:'MPU6050',sub:'SDA GPIO21 · SCL GPIO22 · INT GPIO39',x:390,y:70,w:270,h:110,fill:'#dcecff'},
{id:'sonar',type:'sensor',label:'HC-SR04',sub:'TRIG GPIO5 · ECHO GPIO34',x:690,y:110,w:190,h:100,fill:'#fff3c4'},
{id:'driver',type:'driver',label:'L298N DUAL H-BRIDGE',sub:'ENA 27 · IN1 32 · IN2 33 · IN3 25 · IN4 26 · ENB 14',x:355,y:285,w:340,h:135,fill:'#f05b28'},
{id:'left',type:'motor',label:'LEFT MOTOR',sub:'OUT1 / OUT2',x:20,y:330,w:150,h:82,fill:'#e7fff0'},
{id:'right',type:'motor',label:'RIGHT MOTOR',sub:'OUT3 / OUT4',x:735,y:330,w:150,h:82,fill:'#e7fbff'},
{id:'led',type:'status',label:'STATUS LEDs ×4',sub:'GPIO4 · 16 · 17 · 23 · 220Ω',x:80,y:535,w:300,h:78,fill:'#ffe8eb'},
{id:'battery',type:'power',label:'BATTERY + SWITCH',sub:'Buck → ESP32 / L298N',x:590,y:515,w:260,h:98,fill:'#fff0ae'},
{id:'level',type:'note',label:'مقسم جهد إلزامي',sub:'Echo 5V → 3.3V قبل GPIO34',x:690,y:235,w:190,h:58,fill:'#fff5d8'}],connections:[
['esp','mpu','GPIO21 → SDA · GPIO22 → SCL','i2c'],['esp','mpu','3V3 → VCC','power'],['esp','driver','GPIO27/14 → ENA/ENB','control'],['esp','driver','GPIO32/33/25/26 → DIR','control'],['esp','sonar','GPIO5 → TRIG','sensor'],['sonar','level','ECHO عبر مقسم الجهد','sensor'],['driver','left','OUT1 / OUT2','motorL'],['driver','right','OUT3 / OUT4','motorR'],['battery','driver','VMOTOR +','power'],['esp','led','GPIO4/16/17/23','signal'],['esp','driver','GND مشترك','gnd']]}
};
let mode='arduino',zoom=1, currentData=null;
const $=id=>document.getElementById(id);
const colors={power:'#d52d35',gnd:'#202830',i2c:'#8153c8',control:'#e18b18',sensor:'#c29109',motorL:'#168451',motorR:'#1597bb',signal:'#2e72cd'};
function jsonSample(){return JSON.stringify({mode,title:samples[mode].title,components:samples[mode].components.map(({id,type,label,sub,x,y,w,h,fill})=>({id,type,label,sub,x,y,w,h,fill})),connections:samples[mode].connections.map(([from,to,label,color])=>({from,to,label,color}))},null,2)}
function updateLines(){const n=$('jsonEditor').value.split('\n').length;$('lineNumbers').textContent=Array.from({length:n},(_,i)=>i+1).join('\n')}
function parse(){try{const parsed=JSON.parse($('jsonEditor').value);if(!parsed||!Array.isArray(parsed.components)||!Array.isArray(parsed.connections))throw new Error('يجب أن يحتوي JSON على components و connections');const ids=parsed.components.map(n=>n.id);if(ids.some((id,i)=>!id||ids.indexOf(id)!==i))throw new Error('يوجد id مكرر أو فارغ في components');const missing=parsed.connections.flatMap(c=>[c.from,c.to]).filter(id=>!ids.includes(id));if(missing.length)throw new Error('توصيل يشير إلى مكوّن غير موجود: '+missing[0]);currentData=parsed;$('errorBox').hidden=true;$('statusText').textContent='تم تحليل JSON بنجاح';$('stats').textContent=parsed.components.length+' مكونات · '+parsed.connections.length+' توصيلات';return true}catch(e){$('errorBox').hidden=false;$('errorBox').textContent='خطأ في JSON: '+e.message;$('statusText').textContent='يوجد خطأ في الكود';return false}}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function nodeSvg(n){let extra='';if(n.type==='controller'){extra=`<rect x="${n.x+18}" y="${n.y+48}" width="${n.w-36}" height="55" rx="8" fill="#173451"/><text x="${n.x+n.w/2}" y="${n.y+82}" text-anchor="middle" fill="#d9efff" font-size="16" font-weight="700">CONTROLLER</text>`}else if(n.type==='driver'){extra=`<rect x="${n.x+20}" y="${n.y+42}" width="${n.w-40}" height="48" rx="6" fill="#222b34"/><text x="${n.x+n.w/2}" y="${n.y+72}" text-anchor="middle" fill="#f7cf79" font-size="16" font-weight="700">L298N</text>`}else if(n.type==='sensor'){extra=`<circle cx="${n.x+n.w*.32}" cy="${n.y+53}" r="17" fill="#fff" stroke="#6d8294" stroke-width="3"/><circle cx="${n.x+n.w*.68}" cy="${n.y+53}" r="17" fill="#fff" stroke="#6d8294" stroke-width="3"/>`}else if(n.type==='motor'){extra=`<circle cx="${n.x+n.w/2}" cy="${n.y+35}" r="23" fill="#ffd233" stroke="#bd8b08" stroke-width="4"/>`}else if(n.type==='status'){extra='<circle cx="'+(n.x+50)+'" cy="'+(n.y+40)+'" r="10" fill="#ef3340"/><circle cx="'+(n.x+82)+'" cy="'+(n.y+40)+'" r="10" fill="#ef3340"/><circle cx="'+(n.x+114)+'" cy="'+(n.y+40)+'" r="10" fill="#ef3340"/><circle cx="'+(n.x+146)+'" cy="'+(n.y+40)+'" r="10" fill="#ef3340"/>'}return `<g class="node"><rect x="${n.x}" y="${n.y}" width="${n.w}" height="${n.h}" rx="12" fill="${n.fill||'#fff'}" stroke="#294b68" stroke-width="2.4"/><text x="${n.x+n.w/2}" y="${n.y+27}" text-anchor="middle" fill="#173451" font-size="16" font-weight="700">${esc(n.label)}</text>${extra}${n.sub?`<text x="${n.x+n.w/2}" y="${n.y+n.h-12}" text-anchor="middle" fill="#536b7e" font-size="10">${esc(n.sub)}</text>`:''}</g>`}
function center(n){return {x:n.x+n.w/2,y:n.y+n.h/2}}
function connSvg(c,nodes){const a=nodes.find(n=>n.id===c[0]),b=nodes.find(n=>n.id===c[1]);if(!a||!b)return '';const p=center(a),q=center(b),color=colors[c[3]]||'#5c7187';let mid=(p.x+q.x)/2;return `<g><path d="M${p.x},${p.y} L${mid},${p.y} L${mid},${q.y} L${q.x},${q.y}" fill="none" stroke="${color}" stroke-width="4" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray="${c[3]==='gnd'?'0':'0'}" opacity=".92"/><rect x="${mid-52}" y="${(p.y+q.y)/2-10}" width="104" height="20" rx="6" fill="#fff" stroke="${color}" stroke-width="1.3"/><text x="${mid}" y="${(p.y+q.y)/2+4}" text-anchor="middle" fill="${color}" font-size="9" font-weight="700">${esc(c[2])}</text></g>`}
function render(){if(!parse())return;const d=samples[mode];const data=currentData;const nodes=data.components||d.components;const conns=(data.connections||[]).map(c=>Array.isArray(c)?c:[c.from,c.to,c.label,c.color]);const svg=`<svg viewBox="0 0 900 660" xmlns="http://www.w3.org/2000/svg"><rect x="8" y="8" width="884" height="644" rx="18" fill="#fff" stroke="#b7cadd" stroke-width="3"/><text x="450" y="42" text-anchor="middle" fill="#12344d" font-size="22" font-weight="800">${esc(data.title||d.title)}</text><text x="450" y="64" text-anchor="middle" fill="#6c8296" font-size="11">${esc(d.subtitle)}</text>${conns.map(c=>connSvg(c,nodes)).join('')}${nodes.map(nodeSvg).join('')}<text x="28" y="638" fill="#8295a5" font-size="10">افصل البطارية قبل تعديل الأسلاك · الرسم توضيحي وليس مقياسًا ميكانيكيًا</text></svg>`;$('diagram').innerHTML=svg;$('canvasTitle').textContent=data.title||d.title;renderLegend();renderSpecs(d)}
function renderLegend(){const items=[['power','موجب الطاقة'],['gnd','الأرضي المشترك'],['i2c','I2C / بيانات الحساس'],['control','تحكم L298N'],['sensor','HC-SR04'],['motorL','المحرك الأيسر'],['motorR','المحرك الأيمن'],['signal','إشارات الحالة']];$('legend').innerHTML=items.map(([k,t])=>`<span class="legend-item"><i class="legend-line" style="background:${colors[k]}"></i>${t}</span>`).join('')}
function renderSpecs(d){$('specs').innerHTML=`<div class="spec-list"><div class="spec-row"><b>النمط</b><span>${d.title}</span></div><div class="spec-row"><b>المتحكم</b><span>${d.controller}</span></div><div class="spec-row"><b>عدد العناصر</b><span>${d.components.length} مكونات · ${d.connections.length} مسارات</span></div><div class="spec-row"><b>الأرجل المرجعية</b><table class="pin-table">${d.controllerPins.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td></tr>`).join('')}</table></div></div>`}
function setMode(next){mode=next;document.querySelectorAll('.mode').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('jsonEditor').value=jsonSample();updateLines();render()}
$('renderBtn').onclick=render;$('resetBtn').onclick=()=>{setMode(mode)};$('loadJsonBtn').onclick=()=>$('jsonFile').click();$('jsonFile').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{$('jsonEditor').value=reader.result;updateLines();render()};reader.readAsText(file);e.target.value=''});$('jsonEditor').addEventListener('input',()=>{updateLines();if($('autoRender').checked)render()});$('jsonEditor').addEventListener('scroll',()=>{$('lineNumbers').scrollTop=$('jsonEditor').scrollTop});document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$('zoomIn').onclick=()=>{zoom=Math.min(1.4,zoom+.1);$('diagram').style.transform=`scale(${zoom})`;$('zoomLabel').textContent=Math.round(zoom*100)+'%'};$('zoomOut').onclick=()=>{zoom=Math.max(.7,zoom-.1);$('diagram').style.transform=`scale(${zoom})`;$('zoomLabel').textContent=Math.round(zoom*100)+'%'};$('fitBtn').onclick=()=>{zoom=1;$('diagram').style.transform='scale(1)';$('zoomLabel').textContent='100%'};
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
$('downloadJson').onclick=()=>download(`balancebot-${mode}.json`,$('jsonEditor').value,'application/json');$('downloadSvg').onclick=()=>{if(parse()){download(`balancebot-${mode}.svg`,$('diagram').innerHTML,'image/svg+xml')}};
setMode('arduino');
