const MATTER_URL = 'https://cdn.jsdelivr.net/npm/matter-js@0.20.0/+esm';

export class RobotPhysicsWorld {
  constructor(canvas, onStatus = () => {}) { this.canvas = canvas; this.onStatus = onStatus; this.matter = null; this.engine = null; this.runner = null; this.render = null; this.chassis = null; this.leftWheel = null; this.rightWheel = null; this.ready = false; }
  async init() { try { this.matter = await import(MATTER_URL); const { Engine, Render, Runner, Bodies, Composite, Constraint } = this.matter; this.engine = Engine.create({ gravity: { x: 0, y: 0 } }); this.chassis = Bodies.rectangle(300, 150, 190, 90, { frictionAir: 0.06, density: 0.002, chamfer: { radius: 16 }, render: { fillStyle: '#183b56', strokeStyle: '#8ed1dc', lineWidth: 3 } }); this.leftWheel = Bodies.circle(235, 150, 27, { friction: 0.7, frictionAir: 0.08, density: 0.004, render: { fillStyle: '#202d38', strokeStyle: '#f3b64d', lineWidth: 3 } }); this.rightWheel = Bodies.circle(365, 150, 27, { friction: 0.7, frictionAir: 0.08, density: 0.004, render: { fillStyle: '#202d38', strokeStyle: '#f3b64d', lineWidth: 3 } }); Composite.add(this.engine.world, [this.chassis, this.leftWheel, this.rightWheel, Constraint.create({ bodyA: this.chassis, bodyB: this.leftWheel, length: 65, stiffness: 0.8 }), Constraint.create({ bodyA: this.chassis, bodyB: this.rightWheel, length: 65, stiffness: 0.8 })]); this.render = Render.create({ canvas: this.canvas, engine: this.engine, options: { width: 600, height: 300, wireframes: false, background: '#071a2c', pixelRatio: 1 } }); Render.run(this.render); this.runner = Runner.create(); Runner.run(this.runner, this.engine); this.ready = true; this.onStatus('Matter.js loaded · physics running'); return true; } catch (error) { this.ready = false; this.onStatus('Matter.js unavailable · physics offline'); return false; } }
  drive(leftVoltage, rightVoltage) { if (!this.ready) return; const { Body } = this.matter; const left = Number(leftVoltage) / 10; const right = Number(rightVoltage) / 10; const forward = (left + right) * 0.00045; const turn = (right - left) * 0.000018; Body.applyForce(this.chassis, this.chassis.position, { x: Math.cos(this.chassis.angle) * forward, y: Math.sin(this.chassis.angle) * forward }); Body.setAngularVelocity(this.chassis, this.chassis.angularVelocity + turn); }
  pause() { if (!this.matter || !this.runner) return; this.matter.Runner.stop(this.runner); if (this.render) this.matter.Render.stop(this.render); this.ready = false; this.paused = true; }
  resume() { if (!this.matter || !this.engine || this.ready) return; const { Render, Runner } = this.matter; this.render = Render.create({ canvas: this.canvas, engine: this.engine, options: { width: 600, height: 300, wireframes: false, background: '#071a2c', pixelRatio: 1 } }); Render.run(this.render); this.runner = Runner.create(); Runner.run(this.runner, this.engine); this.ready = true; this.paused = false; this.onStatus('Matter.js resumed · physics running'); }
  telemetry() { if (!this.chassis) return { angle: 0, angularVelocity: 0, x: 300, y: 150, vx: 0, vy: 0 }; return { angle: Number(this.chassis.angle) || 0, angularVelocity: Number(this.chassis.angularVelocity) || 0, x: Number(this.chassis.position.x) || 300, y: Number(this.chassis.position.y) || 150, vx: Number(this.chassis.velocity.x) || 0, vy: Number(this.chassis.velocity.y) || 0 }; }
  reset() { if (!this.matter || !this.chassis) return; const { Body } = this.matter; Body.setPosition(this.chassis, { x: 300, y: 150 }); Body.setAngle(this.chassis, 0); Body.setVelocity(this.chassis, { x: 0, y: 0 }); Body.setAngularVelocity(this.chassis, 0); Body.setPosition(this.leftWheel, { x: 235, y: 150 }); Body.setPosition(this.rightWheel, { x: 365, y: 150 }); }
  stop() { if (!this.matter || !this.runner || !this.engine) return; this.matter.Runner.stop(this.runner); this.matter.Render.stop(this.render); this.ready = false; }
}
