import http from 'node:http';
import os from 'node:os';
import path from 'node:path';
import fs from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { spawn } from 'node:child_process';

const port = Number(process.env.PORT || 8787);
const maxBodyBytes = 512 * 1024;
const json = (status, body) => ({ status, body: JSON.stringify(body) });
function run(command, args, cwd) { return new Promise((resolve) => { const child = spawn(command, args, { cwd, env: { ...process.env, ARDUINO_DIRECTORIES_DATA: path.join(cwd, '.arduino-data') } }); let stdout = ''; let stderr = ''; child.stdout.on('data', (chunk) => { stdout += chunk; }); child.stderr.on('data', (chunk) => { stderr += chunk; }); child.on('close', (code) => resolve({ code, stdout, stderr })); child.on('error', (error) => resolve({ code: -1, stdout, stderr: `${stderr}${error.message}` })); }); }
async function readBody(request) { let size = 0; const chunks = []; for await (const chunk of request) { size += chunk.length; if (size > maxBodyBytes) throw new Error('Request body exceeds 512 KiB.'); chunks.push(chunk); } return Buffer.concat(chunks).toString('utf8'); }
async function compile(request) { const body = JSON.parse(await readBody(request)); const board = typeof body.board === 'string' ? body.board : 'arduino:avr:uno'; const code = typeof body.code === 'string' ? body.code : ''; if (!code.trim()) return json(400, { ok: false, error: 'code is required' }); if (!/^[a-z0-9:.-]+$/.test(board)) return json(400, { ok: false, error: 'invalid board name' }); const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'balancebot-build-')); try { await fs.writeFile(path.join(dir, 'sketch.ino'), code, 'utf8'); const result = await run('arduino-cli', ['compile', '--fqbn', board, '--export-binaries', '.'], dir); if (result.code !== 0) return json(422, { ok: false, buildErrors: result.stderr || result.stdout }); const buildRoot = path.join(dir, 'build'); const hexFiles = []; async function collectHexFiles(folder) { for (const entry of await fs.readdir(folder, { withFileTypes: true })) { const entryPath = path.join(folder, entry.name); if (entry.isDirectory()) await collectHexFiles(entryPath); else if (entry.name.endsWith('.hex')) hexFiles.push(entryPath); } } await collectHexFiles(buildRoot); const hexPath = hexFiles[0]; if (!hexPath) return json(500, { ok: false, error: 'arduino-cli completed without a HEX artifact' }); const hex = await fs.readFile(hexPath, 'utf8'); return json(200, { ok: true, board, hex, diagnostics: result.stderr }); } finally { await fs.rm(dir, { recursive: true, force: true }); } }
const server = http.createServer(async (request, response) => { response.setHeader('Access-Control-Allow-Origin', process.env.CORS_ORIGIN || '*'); response.setHeader('Access-Control-Allow-Headers', 'Content-Type'); if (request.method === 'OPTIONS') { response.writeHead(204); response.end(); return; } if (request.method === 'GET' && request.url === '/health') { const result = json(200, { ok: true, service: 'balancebot-arduino-compiler' }); response.writeHead(result.status, { 'Content-Type': 'application/json' }); response.end(result.body); return; } if (request.method === 'POST' && request.url === '/api/compile') { try { const result = await compile(request); response.writeHead(result.status, { 'Content-Type': 'application/json' }); response.end(result.body); } catch (error) { const result = json(400, { ok: false, error: error.message }); response.writeHead(result.status, { 'Content-Type': 'application/json' }); response.end(result.body); } return; } response.writeHead(404, { 'Content-Type': 'application/json' }); response.end(JSON.stringify({ ok: false, error: 'not found' })); });
server.listen(port, '0.0.0.0', () => console.log(`BalanceBot compiler service listening on ${port}`));
